install.packages('swirl',dependencies=TRUE)
library(swirl)
install.packages('rattle',dependencies=TRUE)
library(rattle)
rattle()
a = c(1,2,3,4)
ifelse(a%%2 == 0,"even","odd")
births <- scan("http://robjhyndman.com/tsdldata/data/nybirths.dat")
data()
X=data("AirPassengers")
summary(X)
View(births)
shapes <- c("round","oval","long",
            "round","oval","long",
            "round","oval","long",
            "round","oval","long")
shapes
str(shapes)
pattern <- c("pattern", "pattern", "pattern",
             "plain", "plain", "plain",
             "pattern", "pattern", "pattern",
             "plain", "plain", "plain")
shades <-c("light", "light", "light",
           "light", "light", "light",
           "dark", "dark", "dark",
           "dark", "dark", "dark")
shapes2 <- as.factor(shapes)
str(shapes2)
pattern2 <- as.factor(pattern)
str(pattern2)
summary(pattern2)
counts <- c(2, 0, 3, 1, 3, 2, 9, 0, 2, 1, 11, 2)
abc <- seq(1:10)
abc
bac <- abc/2
bac
seq(1:10)
seq(1,10,by=2)
candy <- data.frame(shapes,pattern,shades,counts)
candy
a = length(counts)
a
View(candy)
if ( a != 0)
{ length(counts)}
length(counts)
kids <- c("John", "Joe", "Cloe")
ages <- c(12,10,8)
d <- data.frame(kids,ages,stringsAsFactors=FALSE)
e <- data.frame(kids,ages,stringsAsFactors=TRUE)
str(d)
str(e)
list
getwd()
setwd("C:/Users/RB185092/")
getwd()
mydata <- read.csv("C:\\Users\\RB185092\\Documents\\Test data.csv")
dim(mydata)
head(mydata)
View(mydata)
install.packages("sas7bdat",dependencies = TRUE)
library(sas7bdat)
mydata3 <- read.sas7bdat("C:\\Users\\RB185092\\Desktop\\Sowmya DS Course\\Simplilearn\\binary.sas7bdat")
View(mydata3)
mydata3
tail(mydata3,n=3)
?system
getwd()
setwd("C:\\Users\\RB185092\\Documents\\")
write.csv(mydata3,"Test_SAS_Data.csv")
data1<- "C:/Users/RB185092/Documents/Sashwath18Monthquestionnaire.pdf"
data2<- "C:\\Users\\RB185092\\Desktop\\Sowmya DS Course\\Test Data\\PDF Docs\\24_12_13_bbcmagazine_10stories.pdf"
data3<- "C:\\Users\\RB185092\\Desktop\\Sowmya DS Course\\Test Data\\PDF Docs\\478026a.pdf"
exe <- "C:\\Program Files (x86)\\xpdfbin-win-3.04\\xpdfbin-win-3.04\\bin32\\pdftotext.exe"
exe
system(paste("\"", exe, "\" \"", data3, "\"", sep = ""), wait=T)
txtfile <- sub(".pdf", ".txt", data2)
txtfile
shell.exec(txtfile);
install_from_swirl("R_Programming")
m <- matrix(c(1:4),2,2)
m
apply(m,1,sum)
apply(m,2,sum)
l <- list(a=c(1,1),b=c(2,2),c=c(3,3))
sapply(l,sum)
install.packages("psych",dependencies = TRUE)
library(psych)
describe(mydata3)
summary(mydata3)
library(swirl)
head(swirl)
swirl()
install_from_swirl("R_Programming_Alt")
install_from_swirl("Data_Analysis")
counts <- table(mtcars$gear)
barplot(counts)
barplot(counts,horiz=TRUE)
head(mtcars)
barplot(counts,main="Simple Bar Plot",xlab ="Improvement",ylab="Frequency")
counts <- table(mtcars$vs,mtcars$gear)
barplot(counts,main="car Distribution by Gears and VS",xlab ="No.of gears",col=c("grey","red"),beside=TRUE)
counts
slices<- c(10,12,4,16,8)
lbls <-c("US","UK","Australia","France","Germany")
pct <- round(slices/sum(slices)*100)
pie(slices,labels=lbls,col=rainbow(5))
install.packages("ggplot2",dependencies=TRUE)
library(plotrix)
pie3D(slices,labels=lbls,explode=0.0,col=rainbow(5))
install.packages("ggplot2",dependencies=TRUE)
install.packages("plotly",dependencies=TRUE)
library(ggplot2)
library(plotly)
hist(mtcars$mpg,breaks=8,col="darkgreen")
density_data <- density(mtcars$mpg)
plot(density_data)
polygon(density_data,col="skyblue",border="black")
plot(density_data,col="skyblue")
weight <- c(2.5,3.2,4.5,5.7,6.4)
baby_age <- c(1,2,3,4,5)
plot(baby_age,weight,type="b")
lines(baby_age,weight)
vec <- c(3,1,2,3,4,5,1,2,3,4,5,1,2,3,10,12,0)
summary(vec)
boxplot(vec,varwidth=TRUE)
install.packages("wordcloud",dependencies=TRUE)
dirname <- "C:\\Users\\RB185092\\Desktop\\Sowmya DS Course\\Test Data\\PDF Docs"
docs <- Corpus(DirSource(dirname), readerControl=list(reader=readPDF))
install.packages("tm",dependencies = TRUE)
install.packages("qdap",dependencies = TRUE)
install.packages("qdapDictionaries",dependencies = TRUE)
install.packages("RColorBrewer",dependencies = TRUE)
install.packages("ggplot2",dependencies = TRUE)
install.packages("Rgraphviz",dependencies = TRUE)
install.packages("scales",dependencies = TRUE)
install.packages("rJava",dependencies=TRUE)
Sys.getenv("JAVA_HOME")
Sys.setenv(JAVA_HOME="C:\\Program Files\\Java\\jre7\\")
library(tm)
library(qdap)
library(qdapDictionaries)
library(ggplot2)
library(scales)
docs <- Corpus(DirSource(dirname), readerControl=list(reader=readPDF))
setwd("C:\\Users\\RB185092\\Desktop\\Sowmya DS Course\\Test Data\\PDF Docs")
library(swirl)
library(tm)
Sys.getenv()

setwd("C:\\Users\\RB185092\\Desktop\\Sowmya DS Course\\Test Data\\")
getwd()
mydata <- read.csv("Test data.csv")
head(mydata)
names(mydata)
dim(mydata)
tail(mydata)
summary(mydata)
plot(mydata$Losses,xlab="Frequency",ylab="Losses",main="Plot of Dependent Variable")
mydata$CappedLosses <- ifelse(mydata$Losses > 1200 ,1200 ,mydata$Losses)
names(mydata)
View(mydata)
summary(mydata)
mydata_ed <- mydata[,-c(9)]
names(mydata_ed)
plot(mydata$Age,mydata$Losses,xlab="Age of Policy Holder",ylab="Losses",main="Plot of Age vs.Losses")
barplot(mydata_ed$Age,mydata_ed$CappedLosses)
boxplot(mydata_ed$CappedLosses)
